source 'http://ruby.taobao.org/'

gem 'rails', '3.2.11'

# Bundle edge Rails instead:
# gem 'rails', :git => 'git://github.com/rails/rails.git'

#gem 'sqlite3'
gem 'mysql2'

gem 'json'
gem 'rest-client'
gem 'resque'
gem 'rack','1.4.1'
gem 'log4r'
gem 'unicorn'
gem 'uuidtools'
